/**
 * Complete list of all majors
 */
export const MAJORS = [
  "Computer Science",
  "Software Engineering",
  "Data Science",
  "Information Technology",
  "Cybersecurity",
  "Biomedical Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Industrial Engineering",
  "Environmental Engineering",
  "Business Administration",
  "Business Management",
  "Marketing",
  "Finance",
  "Accounting",
  "Economics",
  "Entrepreneurship",
  "International Business",
  "Psychology",
  "Clinical Psychology",
  "Cognitive Psychology",
  "Biology",
  "Molecular Biology",
  "Biochemistry",
  "Genetics",
  "Chemistry",
  "Organic Chemistry",
  "Physical Chemistry",
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Physics",
  "Theoretical Physics",
  "Applied Physics",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Public Health",
  "Health Sciences",
  "Graphic Design",
  "Industrial Design",
  "Fashion Design",
  "Architecture",
  "Communications",
  "Journalism",
  "Media Studies",
  "English Literature",
  "History",
  "Political Science",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Education",
  "Early Childhood Education",
  "Special Education",
  "Law",
  "Criminal Justice",
  "Social Work",
  "Art",
  "Music",
  "Theater",
  "Film Studies",
  "Other",
]
